language: go
sudo: false
go:
- 1.13.x
- 1.12.x
- 1.11.x
env:
- GO111MODULE=on
go_import_path: github.com/QasirID/qibo
install:
- go mod tidy
before_script:
- $(exit $(go fmt ./... | wc -l))
- find . -type f -name "*.go" | xargs misspell -error -locale US
- staticcheck ./...
script:
- go test -i -race ./...
#- go test -v -run=TestNoRace -p=1 ./...
